package upgrade.challenge.reservation.domain;

public enum ReservationStatus {
    RESERVATION_CANCELLED, RESERVATION_CONFIRMED, RESERVATION_CHANGE_PENDING, RESERVATION_PENDING, RESERVATION_REJECTED
}
